### ISSUE TITLE
Support for exporting qcgaugeswidget library?

### ISSUE THREAD

**Issue by mwcondino** [UTNuclearRoboticsPublic/gauges#4]
Hello there! I'm currently developing a custom rqt panel, and I'd like to use the underlying `qcgaugewidget` library used in this package as a part of my panel. I have a working branch of this repo on my own machine w/ a modified version of `CMakeLists.txt` that would export the `qcgaugeswidget` library as a catkin library, which would make it a lot easier for me to use in my custom  panel.

I was wondering if it would be possible to open up a PR and merge in this change? Otherwise, I can fork the repo but I figured it might be nice to modify the original repository in case anyone else wants to use the `qcgaugewidget` library in their own `rqt` applications as well.

**Comment by AndyZe** [comment]
I'd be happy to review and hopefully merge a PR!

**Comment by mwcondino** [comment]
> I'd be happy to review and hopefully merge a PR!

Awesome, glad to hear it!
I'm having some trouble pushing my branch to this repo unfortunately, I'm getting a 403 error:
```
remote: Permission to UTNuclearRoboticsPublic/gauges.git denied to mwcondino.
fatal: unable to access 'https://github.com/UTNuclearRoboticsPublic/gauges.git/': The requested URL returned error: 403
```

 Is there a way that I could be added as a contributor for this repo, or am I missing something obvious?

**Comment by AndyZe** [comment]
Usually you would fork it to a public repo you own, then make the pull request from there

**Comment by mwcondino** [comment]
Will do, I'll put one up shortly. Thanks for bearing w/ me, I'm a bit new to open source contribution

**Comment by mwcondino** [comment]
Thanks for the quick review @AndyZe !

Any chance you could possibly issue a new release for this package as well?

**Comment by AndyZe** [comment]
Mmm, I don't have time right now. Sorry. @RobertBlakeAnderson any interest in doing that, or giving @mwcondino write access to the repo?

**Comment by RobertBlakeAnderson** [comment]
I've just released the current commit as ver 1.0.8.

**Comment by AndyZe** [comment]
He means a full ROS release. Like http://wiki.ros.org/action/fullsearch/bloom/Tutorials/ReleaseCatkinPackage?action=fullsearch&context=180&value=linkto%3A%22bloom%2FTutorials%2FReleaseCatkinPackage%22#Releasing_a_new_version_of_a_catkin_package

That's OK, I wouldn't worry about it

**Comment by mwcondino** [comment]
No worries, thanks for the help!
